### ISSUE TITLE
compatibility with ghc 8.0.1

### ISSUE THREAD

**Issue by int-e** [abbradar/unlambda#2]
please bump the upper bound on the base package to 4.10... apart from that the package builds just fine

**Comment by int-e** [comment]
see also https://github.com/lambdabot/lambdabot/issues/145

**Comment by abbradar** [comment]
Fixed by https://github.com/abbradar/unlambda/commit/26157ec5c91eb14c7e19df68a8a9437bf83f4a5e. I'll upload a new version to Hackage shortly.
